### ISSUE TITLE
Example of a filter condition or expression involving nested properties?

### ISSUE THREAD

**Issue by brabster** [awslabs/dynamodb-document-js-sdk#43] opened 2015-08-18 15:57 UTC
Hi,

An example of setting up a filter (and/or query?) where the condition or expression involves nested properties would be useful - I can't see how to do it!

eg. based of your existing doc examples:

```
{
    PartId : "CPU1",
    OnSale: false,
    Discount: null,
    Compatible: {
        Motherboards : ["MB1", "MB2"],
        RAM : ["RAM1"]
    }
};
```

I would like to filter a scan (or perform a query given the right indexes) where `Compatible.RAM = "RAM1"`

**Comment by brabster** [comment] 2015-08-18 16:00
I already tried equivalent of:

```
dynamo.scan({
    TableName: 'whatever',
    ScanFilter: dynamo.Condition('Condition.RAM', 'EQ', 'RAM1')
}, ...
```

**Comment by SamVerschueren** [comment] 2015-09-05 19:44
I use my own self-written [dynongo](https://github.com/SamVerschueren/dynongo) library (on top of this one) and when I want to do this I get

```javascript
MyTabe.find().where({'Condition.RAM': 'RAM1'}).exec();
```

Uses the following params

```json
{
    "TableName": "MyTable",
    "FilterExpression": "#k_Compatible.#k_RAM = :v_Compatible_RAM",
    "ExpressionAttributeNames": {
        "#k_Compatible": "Compatible",
        "#k_RAM": "RAM"
    },
    "ExpressionAttributeValues": {
        ":v_Compatible_RAM": "RAM1"
    }
}
```

Hopefully this is helpfull

**Comment by mikedizon** [comment] 2016-07-07 13:29
@SamVerschueren awesome solution!

**Comment by amcp** [comment] 2017-04-24 01:47
Resolved so closing.

**Closed by amcp** 2017-04-24 01:47 UTC

**Comment by dylan-albertazzi** [comment] 2020-09-20 17:04
You're the man!

**Comment by dylan-albertazzi** [comment] 2020-09-20 17:05
> I use my own self-written [dynongo](https://github.com/SamVerschueren/dynongo) library (on top of this one) and when I want to do this I get
> 
> ```js
> MyTabe.find().where({'Condition.RAM': 'RAM1'}).exec();
> ```
> 
> Uses the following params
> 
> ```json
> {
>     "TableName": "MyTable",
>     "FilterExpression": "#k_Compatible.#k_RAM = :v_Compatible_RAM",
>     "ExpressionAttributeNames": {
>         "#k_Compatible": "Compatible",
>         "#k_RAM": "RAM"
>     },
>     "ExpressionAttributeValues": {
>         ":v_Compatible_RAM": "RAM1"
>     }
> }
> ```
> 
> Hopefully this is helpfull

You're the man!

**Comment by SSF-Developers** [comment] 2021-02-26 14:48
```
    var filterExpression  = "#column.#userNameAttr = :userName";
    var expressionAttributeNames  = {"#column": "permissions","#userNameAttr": "user"};
    var expressionAttributeValues = {":userName": "dev_000000" };
    
    var queryParams = {
        TableName: "MIS_ACCESS",
        FilterExpression: filterExpression,
        ExpressionAttributeNames: expressionAttributeNames,
        ExpressionAttributeValues: expressionAttributeValues
        
    };
    console.log("queryParams",queryParams);
    let promise =  docClient.scan(queryParams).promise();
    let result = await promise;
    console.log("result",result);
```

The 'permissions' column in my DynamoDB holds data in this format:
```
{
  "user": "dev_RahulC.S.A02",
  "access": [100,101]
}
```

The scan operation result
`result { Items: [], Count: 0, ScannedCount: 22 }`


All discussions on SO and other platforms point to this page. Rest all other threads dismiss the possibility of performing a scan operation on object parameters. Can someone please clarify if it is at all possible to perform a scan operation as intended in this question?

**Comment by outemzabetsamy** [comment] 2022-12-14 13:37
@SamVerschueren  Thank you ! you're the man
